# Generated by Django 3.2 on 2021-04-18 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id_ori', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('des_ori', models.TextField()),
                ('dat_ori', models.DateField(auto_now=True)),
            ],
        ),
    ]
