# Generated by Django 3.2.4 on 2021-06-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientation',
            name='nam_ori',
            field=models.CharField(default='teste', max_length=255),
            preserve_default=False,
        ),
    ]
