# Generated by Django 3.2 on 2021-04-18 21:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_personsymptom_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_reg', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nam_reg', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id_sta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nam_sta', models.CharField(max_length=255, unique=True)),
                ('ini_sta', models.CharField(help_text='Sigla do estado', max_length=2, unique=True)),
                ('cou_sta', models.CharField(help_text='Sigla do País do estado', max_length=3)),
                ('id_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.region')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_cit', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nam_cit', models.CharField(max_length=255)),
                ('id_sta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.state')),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id_add', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('add_str', models.CharField(help_text='Rua', max_length=255)),
                ('id_cit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city')),
                ('id_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
        ),
    ]
