# Generated by Django 3.2 on 2021-04-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_per', models.UUIDField(primary_key=True, serialize=False)),
                ('nam_per', models.CharField(max_length=255)),
                ('cpf_per', models.CharField(max_length=255)),
                ('ema_per', models.CharField(max_length=80)),
                ('nas_per', models.DateField()),
                ('tel_per', models.CharField(max_length=30)),
                ('cov_sit', models.CharField(max_length=1)),
                ('wei_per', models.FloatField()),
                ('hei_per', models.FloatField()),
            ],
        ),
    ]
