# Generated by Django 3.2 on 2021-04-18 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id_per',
        ),
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='cov_sit',
            field=models.CharField(default='N', help_text='N para sem covid, S para suspeita, A para positivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf_per',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ema_per',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hei_per',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tel_per',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='wei_per',
            field=models.FloatField(null=True),
        ),
    ]
