# Generated by Django 3.2 on 2021-04-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_personsymptom_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='des_sym',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
