# Generated by Django 3.2 on 2021-04-18 22:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_symptom_des_sym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personsymptom',
            name='id',
        ),
        migrations.AddField(
            model_name='personsymptom',
            name='id_ps',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
